services:
- docker
script:
- echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
after_success:
- make VCS_REF=$TRAVIS_COMMIT push
env:
  global:
    secure: gocrHLDyFABtrGr1DO1Ol3NkCp4A/E30+wu9mW+Z94RzI4uzPu2OYYIcWqxNpvgIae8Kno8j+v7quWV3nsVWxNY9ZfEWbyIl15A7k5RFYegi/KM7pGuXP7L5NufcFMp+FbZ3InRMHog3vxnpvqIUUSfja3N9fTSRYv20CoQ1v10mGhaD1BJLKzWGorRz9LIvvM22woPVXWUsBXr3T2nVo9c2iZmf2pPFQ7DlU1Aj606ePSwiAo0jFqZozol5t+AnDinTHjP2TpryOKG2yKlRUrMkcZ40fGGpvGOzLeM1UjRw9QEcQpiQHm1ZsHh8ZBhquJtXxLB47WBGUomnZV22KHuu7296/y8lPVdJkaPsSU3DPPus2yEKeYxsfEUComfUKSgAwG0P+JTVt8QEDcJ9KrZUVjHowmsn2AKUN+OPfXs6zh3VmvWl9hH4BW21sqeq6/zN/EzRwLIimVO5qI/0QC4CzWnjW6oBlYjBSs9FqT5RNq3MkmzMaEmt6R56dtkJpb21qrsJvovolUWK9J36K/aot/BNa+gvreZoLlXVKkc9DaSbHKfAcGIdVBVAkdsMk5f06gG9eVcigkr9F3c4EbSteDZLyVGYIgmzcl+2esXDRxowTmSWPtxm2hFbeDQkhaSsuH6/mBDNmZqHeGBZHAyR+aMrFqRLHQXuvAE4E4A=
